### PR TITLE
chore(deps): update dependencies to resolve guzzle security problem

### PR DESCRIPTION
**Pull request by c0nst4ntin**
A manual `composer update` to solve the security alert mentioned in: https://github.com/prismicio-community/php-kit/pull/200

### CODE REVIEW

**Comment by c0nst4ntin** [comment]
@angeloashmore Have you got any Idea as to why this commit didn't trigger the CI Checks? Maybe because there were no changes to the actual code?

**Comment by gsteel** [comment]
This one right here is ready to go: https://github.com/prismicio-community/php-kit/pull/192 @c0nst4ntin

**Comment by c0nst4ntin** [comment]
@gsteel Let's move this discussion to the other PR for now

**Comment by c0nst4ntin** [comment]
I will close this for now. Once #207 passes I will add PHP 8.2 and 8.3 to the composer.json and test suite.
Then I will also update the dependencies and tag a new version.

**Pull request closed without merging**
