### PR TITLE
Upstream Merge request - we created a fork because we thought the project was dead :smiley_cat: 

### PR DESCRIPTION
**Pull request by JeroenBoersma**
We love to drop our mirror with the latest fixes, so here it is a major Pull request...

What we did...

- + PHP 8(.1) support
- * fixed all tests
- + splitted all dom richtext logic (same as node/javascript variants)
- * upgrade GuzzleClient

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
updated PHP unit

**Comment by lihbr** [comment]
Hey there, first of all, @angeloashmore and I are really sorry for the delay we're taking getting back to you.

We'd like to organize our process better to ensure the PHP SDK remains maintained and usable by PHP users while providing them with the support they need.

1. The first action we took towards that goal is moving this repository from our company organization (@prismicio) to our community organization (@prismicio-community) to better reflect the maintenance happening on this kit. We also updated the pointer on Packagist.

2. There are currently two PRs that update the kit to support PHP 8:
   - #191, this PR, by @JeroenBoersma
   - #190, by @c0nst4ntin

   Our goal is aligned with yours and we'd also like to support PHP 8 with the kit. We'd value having you onboard throughout that journey.

3. We'd like to meet you, @JeroenBoersma, @c0nst4ntin, and anyone else interested in our PHP kit, so we can coordinate more quickly on making this kit support PHP 8.
   - Would you be up for a call about it? If yes, [please fill in this poll with your email](https://strawpoll.com/polls/YVyP2L7EkgN) so we can schedule something between all of us :)
   - If a call doesn't work for you, we're still really interested hearing from you and establishing a more direct line of communication, please mail me at: [lucie.haberer@prismic.io](mailto:lucie.haberer@prismic.io)

Thank you for your understanding, we're looking forward to seeing the PHP kit get back on track~

**Comment by c0nst4ntin** [comment]
@lihbr Thank you for the update. I replied in the other PR already, stating my point of view. I believe we should shift the communication to just one PR so that the line of argument is easier to follow and understand. As #190 already has multiple people chatting, it might make sense to continue there. But I'm happy to switch to this PR as well

**Comment by c0nst4ntin** [comment]
@JeroenBoersma As **[feat!: support PHP 8 #190](https://github.com/prismicio-community/php-kit/pull/190)** was just merged and released as **[Version 5.2.0](https://github.com/prismicio-community/php-kit/releases/tag/5.2.0)** the majority of this Pull Request became redundant and I will therefore proceed to close this matter. 

Nonetheless, we appreciate your time and afford and thank you for your contribution!

If you would still like to contribute your Fragment changes, please open a new Issue first so we can discuss the benefits, risks and implementation of those changes.

**Pull request closed without merging**
