### PR TITLE
Updates Guzzle and PHP minimum version (7.1 is EOL)

### PR DESCRIPTION
**Pull request by mattiabasone**

### CODE REVIEW

**Comment by jonathan-bird** [comment]
+1 - when is this going to be merged? Seems like they aren't even maintaining this repo.

**Comment by mattiabasone** [comment]
> +1 - when is this going to be merged? Seems like they aren't even maintaining this repo.

@jonathan-bird this repo seems abandoned :\

**Comment by gsteel** [comment]
FWIW, I have an unofficial client that I use and maintain that uses PSR cache/http for 7.3+ [here](https://github.com/netglue/prismic-client)

**Comment by jrbasso** [comment]
I forked this project and applied your changes into that fork. I also generated a new package since this one seems abandoned. You can check out the package in https://packagist.org/packages/zumba/prismic-sdk

**Comment by c0nst4ntin** [comment]
This got solved by #199 and the previous PHP 8 Update
Please upgrade to Version [5.3.0](https://github.com/prismicio-community/php-kit/releases/tag/5.3.0) to make use of this!

If you have any troubles, please leave a comment or open a new issue!
Thank you for your effort and interest in the PHP SDK!

**Pull request closed without merging**
