### PR TITLE
feat (ci): ensure that ci also runs on pullrequests

### PR DESCRIPTION
**Pull request by c0nst4ntin**
As discovered in PR #204 the CI seems to not work on external pull requests. 
I successfully validated this in #206 and found out how to change this.

### CODE REVIEW

**Comment by c0nst4ntin** [comment]
@angeloashmore Can you check if this is okay with you?
Also please take a look at my question in #204 on how to proceed.

**Comment by c0nst4ntin** [comment]
I just quickly also removed all references to travis ci, so that we have a clean slate and there is no future confusion.
You can probably go ahead and remove any projects or config in travis.

The only thing I need to figure out, is how to add the GitHub Pages deployment for the PhpDoc back working with the new workflow. But that wasn't working anyway, so we can drop it for now.

**Comment by angeloashmore** [comment]
Hi @c0nst4ntin, the clean-up looks good! Thanks for removing Travis CI. Feel free to merge when you are ready.

**Review by lihbr — APPROVED** [review]
Good for me too, thank you! 🙏

**Pull request merged**
