### PR TITLE
Guzzle ^7.0 & PHPUnit ^9.0

### PR DESCRIPTION
**Pull request by roelofjan-elsinga**

### CODE REVIEW

**Comment by Ferjgm98** [comment]
Is there any plan to merge this soon?

**Comment by roelofjan-elsinga** [comment]
@Ferjgm98 It seems this repo is abandoned, so I'm using this as a patched version with cweagans/composer-patches

**Comment by jrbasso** [comment]
There was another PR upgrading Guzzle. I forked this project and applied the similar changes into that fork. I also generated a new package since this one seems abandoned. You can check out the package in https://packagist.org/packages/zumba/prismic-sdk

**Comment by roelofjan-elsinga** [comment]
Definitely abandoned, use this instead: https://packagist.org/packages/roelofjan-elsinga/prismic-php 

Or any of the other packages mentioned.

**Comment by c0nst4ntin** [comment]
This got solved by #199 and the previous PHP 8 Update
Please upgrade to Version [5.3.0](https://github.com/prismicio-community/php-kit/releases/tag/5.3.0) to make use of this!

If you have any troubles, please leave a comment or open a new issue!

**Pull request closed without merging**
